name = "fastapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AdlHAAIjcDFmNzFlNjMwYmU4YzE0YzUxODcyZjBkMTYwMWFiMWVjN3AxMA"
UPSTASH_REDIS_REST_URL = "https://apt-stinkbug-55623.upstash.io"